### ISSUE TITLE
Much larger parquet (nyc taxi) to StarRocks error

### ISSUE THREAD

**Issue by alberttwong** [slingdata-io/sling-cli#177]
```
atwong@Albert-CelerData Downloads % sling run --src-stream 'file:///Users/atwong/Downloads/green_tripdata_2023-01.parquet' --tgt-conn STARROCKSLOCAL --tgt-object 'testing.tripdata' --mode full-refresh -d
2024-02-16 08:16:27 DBG Sling version: 1.1.5 (darwin arm64)
2024-02-16 08:16:27 DBG type is file-db
2024-02-16 08:16:27 DBG using source options: {"trim_space":false,"empty_as_null":true,"header":true,"compression":"AUTO","null_if":"NULL","datetime_format":"AUTO","skip_blank_lines":false,"delimiter":",","max_decimals":-1,"transforms":["parse_bit"]}
2024-02-16 08:16:27 DBG using target options: {"datetime_format":"auto","max_decimals":-1,"use_bulk":true,"add_new_columns":true,"adjust_column_type":false,"column_casing":"source"}
2024-02-16 08:16:27 INF connecting to target database (starrocks)
2024-02-16 08:16:27 INF reading from source file system (file)
2024-02-16 08:16:27 DBG listing path: file:///Users/atwong/Downloads/green_tripdata_2023-01.parquet
2024-02-16 08:16:27 DBG ds.1708100187896.b5Z, reading datastream from /Users/atwong/Downloads/green_tripdata_2023-01.parquet [format=parquet]
panic: cannot create dictionary from parquet NULL type

goroutine 102 [running]:
github.com/parquet-go/parquet-go.(*nullType).NewDictionary(0x14000cab110?, 0x0?, 0x0?, {0x0?, 0x0?, {0x0?, 0x0?, 0x0?}, {0x0?, 0x10569eb08?, ...}})
	/Users/fritz/go/pkg/mod/github.com/parquet-go/parquet-go@v0.20.0/type.go:2221 +0x2c
github.com/parquet-go/parquet-go.(*Column).decodeDictionary(0x14000cab110, {0x105526220?}, 0x14000d0c301?, 0x1d9f140?)
	/Users/fritz/go/pkg/mod/github.com/parquet-go/parquet-go@v0.20.0/column.go:793 +0x348
github.com/parquet-go/parquet-go.(*filePages).readDictionaryPage(0x14000a546e0, 0x1400193cd20?, 0x1400193cd20?)
	/Users/fritz/go/pkg/mod/github.com/parquet-go/parquet-go@v0.20.0/file.go:675 +0x3c
github.com/parquet-go/parquet-go.(*filePages).ReadPage(0x14000a546e0)
	/Users/fritz/go/pkg/mod/github.com/parquet-go/parquet-go@v0.20.0/file.go:611 +0x120
github.com/parquet-go/parquet-go.(*rowGroupRows).ReadRows(0x140009fe000, {0x14000ff6a98, 0x1, 0x1})
	/Users/fritz/go/pkg/mod/github.com/parquet-go/parquet-go@v0.20.0/row_group.go:336 +0x2c0
github.com/parquet-go/parquet-go.(*reader).ReadRows(0x1400100c1f0, {0x14000ff6a98?, 0x1?, 0x1?})
	/Users/fritz/go/pkg/mod/github.com/parquet-go/parquet-go@v0.20.0/reader.go:526 +0xc0
github.com/parquet-go/parquet-go.(*Reader).Read(0x1400100c1b0, {0x1050a6a20?, 0x1400019c810})
	/Users/fritz/go/pkg/mod/github.com/parquet-go/parquet-go@v0.20.0/reader.go:407 +0x18c
github.com/slingdata-io/sling-cli/core/dbio/iop.(*Parquet).nextFunc(0x14000c54b10, 0x140014103c0)
	/Users/fritz/gh-runner/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/parquet.go:74 +0x7c
github.com/slingdata-io/sling-cli/core/dbio/iop.(*Iterator).next(0x140014103c0)
	/Users/fritz/gh-runner/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/datastream.go:1696 +0x108
github.com/slingdata-io/sling-cli/core/dbio/iop.(*Datastream).Start(0x14000e58340)
	/Users/fritz/gh-runner/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/datastream.go:425 +0xb4
github.com/slingdata-io/sling-cli/core/dbio/iop.(*Datastream).ConsumeParquetReaderSeeker(0x14000e58340, {0x1056412e8?, 0x14000d06150?})
	/Users/fritz/gh-runner/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/datastream.go:827 +0x1ec
github.com/slingdata-io/sling-cli/core/dbio/filesys.(*LocalFileSysClient).GetDatastream.func1()
	/Users/fritz/gh-runner/sling-cli/_work/sling-cli/sling-cli/core/dbio/filesys/fs_local.go:121 +0x4d8
created by github.com/slingdata-io/sling-cli/core/dbio/filesys.(*LocalFileSysClient).GetDatastream in goroutine 15
	/Users/fritz/gh-runner/sling-cli/_work/sling-cli/sling-cli/core/dbio/filesys/fs_local.go:103 +0x5e0
```

file: https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page

**Comment by flarco** [comment]
Fixed in #173. Closing.
