### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by OneCyrus** [slingdata-io/sling-cli#319]
## Issue Description

- Description of the issue: we get random panic exceptions. it's very random.

- Sling version (`sling --version`): 1.2.11

- Operating System (`linux`, `mac`, `windows`): linux

- Log Output (please run command with `-d`): 

```
[90m2024-06-07 13:06:37[0m [33mDBG[0m Sling version: 1.2.11 (linux amd64)
[90m2024-06-07 13:06:37[0m [33mDBG[0m type is db-file
[90m2024-06-07 13:06:37[0m [33mDBG[0m using source options: {"empty_as_null":false,"null_if":"NULL","datetime_format":"AUTO","max_decimals":-1}
[90m2024-06-07 13:06:37[0m [33mDBG[0m using target options: {"header":true,"compression":"auto","concurrency":7,"datetime_format":"auto","delimiter":",","file_max_rows":0,"file_max_bytes":0,"max_decimals":-1,"use_bulk":true,"add_new_columns":true,"adjust_column_type":false,"column_casing":"source"}
[90m2024-06-07 13:06:37[0m [32mINF[0m connecting to source database (sqlserver)
[90m2024-06-07 13:06:37[0m [33mDBG[0m opened "sqlserver" connection (conn-sqlserver-GUL)
[90m2024-06-07 13:06:37[0m [32mINF[0m reading from source database
[90m2024-06-07 13:06:37[0m [33mDBG[0m [36mSELECT * FROM [SLA][0m
[90m2024-06-07 13:06:37[0m [32mINF[0m writing to target file system (file)
[90m2024-06-07 13:06:37[0m [33mDBG[0m writing to file:///runner/project/datacollection/sources/sla.json [fileRowLimit=0 fileBytesLimit=0 compression=auto concurrency=7 useBufferedStream=false fileFormat=json]
1s 17,333 ? p/s 3.8 MB | 35% MEM | 67% CPU 2s 35,947 18615 r/s 7.9 MB | 36% MEM | 80% CPU panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1614f27]

goroutine 121 [running]:
github.com/slingdata-io/sling-cli/core/dbio/iop.(*Batch).ID(...)
	/github/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/datastream_batch.go:63
github.com/slingdata-io/sling-cli/core/dbio/filesys.(*BaseFileSysClient).WriteDataflowReady.func1.1({0x3ca85a0, 0xc0012a0210}, 0xc0012d8980, {0xc001028280, 0x4a})
	/github/sling-cli/_work/sling-cli/sling-cli/core/dbio/filesys/fs.go:685 +0x127
created by github.com/slingdata-io/sling-cli/core/dbio/filesys.(*BaseFileSysClient).WriteDataflowReady.func1.2 in goroutine 119
	/github/sling-cli/_work/sling-cli/sling-cli/core/dbio/filesys/fs.go:732 +0x6bb
```

**Comment by flarco** [comment]
Thanks for reporting. Fixed here: https://github.com/slingdata-io/sling-cli/pull/318/commits/d85c93c6ad2324b07c08d189e8da26c4f46c80dc
