### ISSUE TITLE
SFTP Replication fails if the wildcard stream url dosen't return any files

### ISSUE THREAD

**Issue by lethaldose** [slingdata-io/sling-cli#372]
## Issue Description

- Description of the issue:  

I have sling replication config setup for copying csv files from sftp to bigquery. For matching csv files in sftp folder i am giving a wildcard string like `11111/feed-2024-03-15-*.csv`. If no matching files are found the replication fails. I debugged the issue locally. it has 2 issues as below.

1. Replication Incorrectly sets the file type format is JSON. The if check in `fs.go` causes this: `GetDataflow()` --> `isFiletype(FileTypeJson, nodes.URIs()...)`. isFiletype function checks the count of files in directory. in this case 1 == 1 so it returns true
2. Since no matching files are found. The directory is skipped. And then the reader channel is closed and for some reason `ConsumeJsonReaderChl` gets called and fails at nextJSON setting reader uri. 

Is this expected behavior or should it exit gracefully with a info message that no files are found.

- Sling version (`sling --version`):  1.2.15

- Operating System (`linux`, `mac`, `windows`): mac

- Replication Configuration: 

```yaml
source: SOURCE_SFTP
target: BIGQUERY_TEST

defaults:
  mode: snapshot
  single: true
  source_options:
    format: csv
streams:
  "11111/feed-2024-03-15-*.csv":
    object: 11111_feed
```

- Log Output (please run command with `-d`): 

```
sling run -d -r dagster_etl/assets/local_replication.yaml      default at  15:04:20
2024-09-04 17:09:10 INF Sling Replication [1 streams] | SOURCE_SFTP -> BIGQUERY_TEST
2024-09-04 17:09:17 DBG opened "sftp" connection (conn-sftp-E6Y)
2024-09-04 17:09:24 DBG opened "sftp" connection (conn-sftp-q7Z)
2024-09-04 17:09:29 DBG opened "sftp" connection (conn-sftp-xKo)

2024-09-04 17:09:29 INF [1 / 1] running stream 11111/feed-2024-03-15-*.csv
2024-09-04 17:09:30 DBG Sling version: 1.2.15 (darwin arm64)
2024-09-04 17:09:30 DBG type is file-db
2024-09-04 17:09:30 DBG using: {"columns":{"*":"string"},"transforms":["replace_non_printable","replace_0x00"]}
2024-09-04 17:09:30 DBG using source options: {"trim_space":false,"empty_as_null":true,"header":true,"fields_per_rec":-1,"compression":"auto","format":"csv","null_if":"\\N","datetime_format":"AUTO","skip_blank_lines":false,"max_decimals":9}
2024-09-04 17:09:30 DBG using target options: {"datetime_format":"2006-01-02 15:04:05.000000-07","file_max_rows":0,"max_decimals":9,"use_bulk":true,"add_new_columns":true,"adjust_column_type":false,"column_casing":"source"}
2024-09-04 17:09:31 DBG opened "bigquery" connection (conn-bigquery-Bo0)
2024-09-04 17:09:31 INF connecting to target database (bigquery)
2024-09-04 17:09:32 INF reading from source file system (sftp)
2024-09-04 17:09:38 DBG opened "sftp" connection (conn-sftp-vAi)
2024-09-04 17:09:44 DBG reading single datastream from sftp://example.com:22/11111/feed-2024-03-15-*.csv [format=json]
2024-09-04 17:09:44 DBG merging json readers of 1 files [concurrency=8] from sftp://example.com:22/11111/feed-2024-03-15-*.csv
2024-09-04 17:09:44 DBG skipping sftp://example.com:22/11111/ because is not file
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x100e5c664]

goroutine 141 [running]:
github.com/slingdata-io/sling-cli/core/dbio/iop.(*Datastream).ConsumeJsonReaderChl.func1(0x0)
	/Users/github/gh-runner/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/datastream.go:1013 +0x24
github.com/slingdata-io/sling-cli/core/dbio/iop.(*Datastream).ConsumeJsonReaderChl(0x14000cd4340, 0x14000d1e420, 0x0)
	/Users/github/gh-runner/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/datastream.go:1036 +0xa0
github.com/slingdata-io/sling-cli/core/dbio/filesys.MergeReaders({0x104540260, 0x140001e64b0}, {0x10259ad14, 0x4}, {0x14000c953b0, 0x1, 0x1}, 0x0)
	/Users/github/gh-runner/sling-cli/_work/sling-cli/sling-cli/core/dbio/filesys/fs.go:1215 +0x97c
github.com/slingdata-io/sling-cli/core/dbio/filesys.GetDataflow.func1()
	/Users/github/gh-runner/sling-cli/_work/sling-cli/sling-cli/core/dbio/filesys/fs.go:961 +0x5f4
created by github.com/slingdata-io/sling-cli/core/dbio/filesys.GetDataflow in goroutine 121
	/Users/github/gh-runner/sling-cli/_work/sling-cli/sling-cli/core/dbio/filesys/fs.go:932 +0x294
```

**Comment by flarco** [comment]
Can you try the latest version? There were some improvements with wildcards in general.

**Comment by lethaldose** [comment]
yes it works in `v1.2.18`. thank you very much from prompt response 👍

**Comment by lethaldose** [comment]
works in latest 1.2.18 version
