### ISSUE TITLE
Cannot define columns when reading from a JSON file.

### ISSUE THREAD

**Issue by ernestoalejo** [slingdata-io/sling-cli#463]
## Issue Description

I encountered an issue when processing a JSON file containing a list of records. During auto-parsing, the `id` column's type is inferred as a number instead of a string, even when using the `to_string` call. To address this, I attempted to explicitly define the columns.

The problem arises during the first iteration of the loop, where it appears that no columns are defined. As a result, the types are inferred again [here](https://github.com/slingdata-io/sling-cli/blob/main/core/dbio/iop/json.go#L211). After the first loop iteration, four columns are defined. However, the row is [created](https://github.com/slingdata-io/sling-cli/blob/main/core/dbio/iop/json.go#L190) with only the original two columns, leading to a panic at line 211.

To resolve this, I added the following code [here](https://github.com/slingdata-io/sling-cli/blob/main/core/dbio/iop/datastream.go#L1098):

```go
for _, col := range ds.Columns {
  jsNew.ColumnMap[col.Name] = &col
}
```

This change resolves the issue, but I am not deeply familiar with the codebase and cannot confirm if this is the correct solution. I would appreciate your review before submitting this PR.

Additionally the problem of rows with a wrong column count seems like a secondary bug to be addressed separately.

---

- Sling version (`sling --version`): 
Version: 1.3.2

- Operating System (`linux`, `mac`, `windows`): 
linux

- Replication Configuration: 

```yaml
source: LOCAL
target: SLING_URL
defaults:
  mode: full-refresh
env:
  target: '${DATABASE}_stg'

streams:
  'file://./data/extra-corto.json':
    object: '{target}.historico'
    source_options:
      jmespath: 'Report[*].{id: to_string(@.ResellerDetailId), data: to_string(@)}'
      flatten: true
    columns:
      id: string
      data: json
```

- Log Output (please run command with `-d`): 

```
WARN[0000]log.go:244 gosnowflake.(*defaultLogger).Warn DBUS_SESSION_BUS_ADDRESS envvar looks to be not set, this can lead to runaway dbus-daemon processes. To avoid this, set envvar DBUS_SESSION_BUS_ADDRESS=$XDG_RUNTIME_DIR/bus (if it exists) or DBUS_SESSION_BUS_ADDRESS=/dev/null.
2024-12-10 22:15:47 DBG opened "file" connection (conn-file-DJY)
2024-12-10 22:15:47 INF Sling Replication | LOCAL -> SLING_URL | file://./data/extra-corto.json
2024-12-10 22:15:47 DBG Sling version: 1.3.2 (linux amd64)
2024-12-10 22:15:47 DBG type is file-db
2024-12-10 22:15:47 DBG using: {"columns":[{"name":"id","type":"string"},{"name":"data","type":"json"}],"mode":"full-refresh","transforms":null}
2024-12-10 22:15:47 DBG using source options: {"empty_as_null":true,"header":true,"flatten":true,"fields_per_rec":-1,"compression":"auto","null_if":"NULL","datetime_format":"AUTO","skip_blank_lines":false,"max_decimals":-1,"jmespath":"Report[*].{id: to_string(@.ResellerDetailId), data: to_string(@)}"}
2024-12-10 22:15:47 DBG using target options: {"datetime_format":"auto","file_max_rows":0,"max_decimals":-1,"use_bulk":true,"add_new_columns":true,"adjust_column_type":false,"column_casing":"source"}
2024-12-10 22:15:47 DBG opened "mysql" connection (conn-mysql-87o)
2024-12-10 22:15:47 INF connecting to target database (mysql)
2024-12-10 22:15:47 INF reading from source file system (file)
2024-12-10 22:15:47 DBG opened "file" connection (conn-file-QVR)
2024-12-10 22:15:47 DBG reading single datastream from file://./data/extra-corto.json [format=json]
2024-12-10 22:15:47 DBG merging json readers of 1 files [concurrency=3] from file://./data/extra-corto.json
2024-12-10 22:15:47 DBG processing reader from file://./data/extra-corto.json
2024-12-10 22:15:47 INF execution failed

--- dataflow.go:564 PushStreamChan ---

--- fs.go:989 func1 ---
--- fs.go:1269 MergeReaders ---
--- datastream.go:1147 ConsumeJsonReaderChl ---
--- datastream.go:688 Start ---
--- datastream.go:2728 next ---
--- datastream.go:1110 func2 ---
--- json.go:151 NextFunc ---
--- json.go:211 parseRecords ---
--- panic.go:114 goPanicIndex ---
--- panic.go:770 gopanic ---
--- datastream.go:672 func1 ---
panic occurred! runtime.boundsError{x:2, y:2, signed:true, code:0x0}
goroutine 132 [running]:
runtime/debug.Stack()
        /home/larco/gh-actions/sling-cli/_work/_tool/go/1.22.7/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/slingdata-io/sling-cli/core/dbio/iop.(*Datastream).Start.func1()
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/datastream.go:672 +0x3d
panic({0x3604d20?, 0xc000feaf30?})
        /home/larco/gh-actions/sling-cli/_work/_tool/go/1.22.7/x64/src/runtime/panic.go:770 +0x132
github.com/slingdata-io/sling-cli/core/dbio/iop.(*jsonStream).parseRecords(0xc0011dac80, {0xc0006351c0, 0x5, 0xc000e0d320?})
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/json.go:211 +0xa75
github.com/slingdata-io/sling-cli/core/dbio/iop.(*jsonStream).NextFunc(0xc0011dac80, 0xc0014b8cc0)
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/json.go:151 +0x686
github.com/slingdata-io/sling-cli/core/dbio/iop.(*Datastream).ConsumeJsonReaderChl.func2(0xc0014b8cc0)
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/datastream.go:1110 +0x6b
github.com/slingdata-io/sling-cli/core/dbio/iop.(*Iterator).next(0xc0014b8cc0)
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/datastream.go:2728 +0x27a
github.com/slingdata-io/sling-cli/core/dbio/iop.(*Datastream).Start(0xc000de6008)
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/datastream.go:688 +0x14d0
github.com/slingdata-io/sling-cli/core/dbio/iop.(*Datastream).ConsumeJsonReaderChl(0xc000de6008, 0xc001680060, 0x0)
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/datastream.go:1147 +0x3b4
github.com/slingdata-io/sling-cli/core/dbio/filesys.MergeReaders({0x46a4008, 0xc00157e5a0}, {0x38257dc, 0x4}, {0xc000d44120, 0x1, 0x1}, {0x0, {0x0, 0x0, ...}, ...})
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/filesys/fs.go:1269 +0xb8a
github.com/slingdata-io/sling-cli/core/dbio/filesys.GetDataflow.func1()
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/filesys/fs.go:989 +0x770
created by github.com/slingdata-io/sling-cli/core/dbio/filesys.GetDataflow in goroutine 125
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/filesys/fs.go:960 +0x28d


context canceled

context canceled

2024-12-10 22:15:48 INF Sling Replication Completed in 0s | LOCAL -> SLING_URL | 0 Successes | 1 Failures

fatal:
--- proc.go:271 main ---
--- sling_cli.go:452 main ---
--- sling_cli.go:488 cliInit ---
--- cli.go:286 CliProcess ---
~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
--- sling_run.go:199 processRun ---

--------------------------- file://./data/extra-corto.json ---------------------------
--- task_run.go:125 func2 ---
~ could not read from file
--- task_run.go:468 runFileToDB ---
~ Could not FileSysReadDataflow for file
--- task_run_read.go:256 ReadFromFile ---
~ error getting dataflow
--- fs.go:579 ReadDataflow ---
--- fs.go:1052 GetDataflow ---
~ dataflow error while waiting for ready state
--- dataflow.go:644 WaitReady ---

--- dataflow.go:564 PushStreamChan ---

--- fs.go:989 func1 ---
--- fs.go:1269 MergeReaders ---
--- datastream.go:1147 ConsumeJsonReaderChl ---
--- datastream.go:688 Start ---
--- datastream.go:2728 next ---
--- datastream.go:1110 func2 ---
--- json.go:151 NextFunc ---
--- json.go:211 parseRecords ---
--- panic.go:114 goPanicIndex ---
--- panic.go:770 gopanic ---
--- datastream.go:672 func1 ---
panic occurred! runtime.boundsError{x:2, y:2, signed:true, code:0x0}
goroutine 132 [running]:
runtime/debug.Stack()
        /home/larco/gh-actions/sling-cli/_work/_tool/go/1.22.7/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/slingdata-io/sling-cli/core/dbio/iop.(*Datastream).Start.func1()
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/datastream.go:672 +0x3d
panic({0x3604d20?, 0xc000feaf30?})
        /home/larco/gh-actions/sling-cli/_work/_tool/go/1.22.7/x64/src/runtime/panic.go:770 +0x132
github.com/slingdata-io/sling-cli/core/dbio/iop.(*jsonStream).parseRecords(0xc0011dac80, {0xc0006351c0, 0x5, 0xc000e0d320?})
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/json.go:211 +0xa75
github.com/slingdata-io/sling-cli/core/dbio/iop.(*jsonStream).NextFunc(0xc0011dac80, 0xc0014b8cc0)
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/json.go:151 +0x686
github.com/slingdata-io/sling-cli/core/dbio/iop.(*Datastream).ConsumeJsonReaderChl.func2(0xc0014b8cc0)
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/datastream.go:1110 +0x6b
github.com/slingdata-io/sling-cli/core/dbio/iop.(*Iterator).next(0xc0014b8cc0)
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/datastream.go:2728 +0x27a
github.com/slingdata-io/sling-cli/core/dbio/iop.(*Datastream).Start(0xc000de6008)
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/datastream.go:688 +0x14d0
github.com/slingdata-io/sling-cli/core/dbio/iop.(*Datastream).ConsumeJsonReaderChl(0xc000de6008, 0xc001680060, 0x0)
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/iop/datastream.go:1147 +0x3b4
github.com/slingdata-io/sling-cli/core/dbio/filesys.MergeReaders({0x46a4008, 0xc00157e5a0}, {0x38257dc, 0x4}, {0xc000d44120, 0x1, 0x1}, {0x0, {0x0, 0x0, ...}, ...})
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/filesys/fs.go:1269 +0xb8a
github.com/slingdata-io/sling-cli/core/dbio/filesys.GetDataflow.func1()
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/filesys/fs.go:989 +0x770
created by github.com/slingdata-io/sling-cli/core/dbio/filesys.GetDataflow in goroutine 125
        /home/larco/gh-actions/sling-cli/_work/sling-cli/sling-cli/core/dbio/filesys/fs.go:960 +0x28d


context canceled
```

**Comment by flarco** [comment]
Thanks for the details.

Added it [here](https://github.com/slingdata-io/sling-cli/commit/30dab2b0b49268977e8062632c030ecb24e38c46#diff-523acdbf3a53c3e4d9be90da2e5896e64c530b84e7e79944f70c3268fc6a01efR47-R51).

Binary available in the dev-build: https://github.com/slingdata-io/sling-cli?tab=readme-ov-file#automated-dev-builds

Closing.
